### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by sumaiyamannan** [adamdehaven/vuepress-plugin-custom-tooltip#2]
**Describe the bug**
I have followed the instructions to install it in a vuepress project

**To Reproduce**

Run npm install @adamdehaven/vuepress-plugin-custom-tooltip
And _plugins: ['@adamdehaven/vuepress-plugin-custom-tooltip'],_ config.js file
And add the below to a to the .md file
What is <VueCustomTooltip label="This is a tooltip">a tooltip</VueCustomTooltip>?

**Expected behavior**
I expected the tooltip to show

** What is actually happening **
Plugin is not working

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Package Version latest

**Additional context**
During vuepress dev docs, I received the below error
warning An error was encountered in plugin "@adamdehaven/vuepress-plugin-custom-tooltip"

**Comment by sumaiyamannan** [comment]
I found the solution from here https://github.com/vuejs/vuepress/issues/2033
Basically use yarn instead of npm for the installation and the issue is sorted

**Comment by adamdehaven** [comment]
According [to the docs](https://vuepress.vuejs.org/guide/getting-started.html#prerequisites), you should use yarn for VuePress projects.
